work_dir: ../work_dir/noiseHAR/ntu120_mutual/ctrgcn/xsub-joint-motion-4
seed: 336
feeder: feeder.feeder_ntu.Feeder
train_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/mutual/CSub/train_mutual_data.npy
  label_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/mutual/CSub/train_mutual_label.npy
  random_rot: True
  window_size: 64
  p_interval: [0.5, 1]
  vel: True
test_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/mutual/CSub/test_mutual_data.npy
  label_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/mutual/CSub/test_mutual_label.npy
  window_size: 64
  p_interval: [0.95]
  vel: True
# model
model: net.ctrgcn.Model
model_args:
  num_class: 26
  num_point: 25
  num_person: 2
  graph: net.ctrgcn.Graph
  graph_args:
    labeling_mode: 'spatial'

weight_decay: 0.0004
base_lr: 0.1
#lr_decay_type: 'cosine'
step: [35, 55]
#start_epoch: 40
# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 65
warmup_epoch: 5