work_dir: ../work_dir/noiseHAR/ntu120_mutual/ctrgcn/xsub-joint
seed: 337
feeder: feeder.feeder_ntu.Feeder
train_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/mutual/CSub/train_mutual_data.npy
  label_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/mutual/CSub/train_mutual_label.npy
  random_rot: True
  window_size: 64
  p_interval: [0.5, 1]
test_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/mutual/CSub/test_mutual_data.npy
  label_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/mutual/CSub/test_mutual_label.npy
  window_size: 64
  p_interval: [0.95]
# model
model: net.ctrgcn.Model
model_args:
  num_class: 26
  num_point: 25
  num_person: 2
  graph: net.ctrgcn.Graph
  graph_args:
    labeling_mode: 'spatial'

weight_decay: 0.0001
base_lr: 0.1
lr_decay_type: 'cosine'
#step: [10, 50]
#start_epoch: 40
# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 50