work_dir: ../work_dir/noiseHAR/ntu120_mutual/stgcn_mutual/xsub_symmetric

# feeder
feeder: feeder.feeder.Feeder_mutual
train_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU120_frame64_mutual/xsub/train_mutual_position.npy
  label_path: /data/wangkun/project/datasets/NTU120_frame64_mutual/xsub/train_mutual_label.npy
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  random_rot_theta: 0.3
test_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU120_frame64_mutual/xsub/val_mutual_position.npy
  label_path: /data/wangkun/project/datasets/NTU120_frame64_mutual/xsub/val_mutual_label.npy
  shear_amplitude: -1
  temperal_padding_ratio: -1
  random_rot_theta: -1

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 26
  dropout: 0.5
  edge_importance_weighting: True
  graph: net.st_gcn.MutualGraph
  graph_args:
    dataset: 'ntu120_mutual'
    graph: 'mutual'
    labeling: 'spatial'

weight_decay: 0.0001
base_lr: 0.1
lr_decay_type: 'cosine'
#step: [10, 50]
#start_epoch: 40
# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 50
phase: 'train'



